package config

import (
	"fmt"
	"os"
	"slices"
	"strconv"
	"strings"
	"time"

	toml "github.com/pelletier/go-toml/v2"

	noisepkg "github.com/aeddi/gno-watchtower/pkg/noise"
	"github.com/aeddi/gno-watchtower/pkg/tomlutil"
)

// Valid log levels, in rank order.
var validLogLevels = []string{"debug", "info", "warn", "error"}

// Duration wraps time.Duration to support TOML string values like "3s", "30s".
type Duration = tomlutil.Duration

// Byte size multipliers (package-private — ByteSize.UnmarshalText consumes these).
const (
	kb = 1024
	mb = 1024 * kb
	gb = 1024 * mb
)

// Log source values.
const (
	LogSourceDocker   = "docker"
	LogSourceJournald = "journald"
)

// Resource source values.
const (
	ResSourceHost   = "host"
	ResSourceDocker = "docker"
	ResSourceBoth   = "both"
)

// ByteSize is an int64 that unmarshals from TOML strings like "1MB", "512KB", "1GB".
// Plain integers are also accepted (e.g. "1024" = 1024 bytes).
type ByteSize int64

func (b *ByteSize) UnmarshalText(text []byte) error {
	s := strings.ToUpper(strings.TrimSpace(string(text)))
	for _, m := range []struct {
		suffix string
		mult   int64
	}{
		{"GB", gb},
		{"MB", mb},
		{"KB", kb},
	} {
		if strings.HasSuffix(s, m.suffix) {
			n, err := strconv.ParseInt(strings.TrimSuffix(s, m.suffix), 10, 64)
			if err != nil {
				return fmt.Errorf("invalid byte size %q: %w", string(text), err)
			}
			*b = ByteSize(n * m.mult)
			return nil
		}
	}
	n, err := strconv.ParseInt(s, 10, 64)
	if err != nil {
		return fmt.Errorf("invalid byte size %q: %w", string(text), err)
	}
	*b = ByteSize(n)
	return nil
}

func (b ByteSize) MarshalText() ([]byte, error) {
	v := int64(b)
	switch {
	case v > 0 && v%gb == 0:
		return fmt.Appendf(nil, "%dGB", v/gb), nil
	case v > 0 && v%mb == 0:
		return fmt.Appendf(nil, "%dMB", v/mb), nil
	case v > 0 && v%kb == 0:
		return fmt.Appendf(nil, "%dKB", v/kb), nil
	default:
		return strconv.AppendInt(nil, v, 10), nil
	}
}

// Placeholder values used in generated configs for fields that need user input.
// Package-private — external code uses IsPlaceholder to detect them.
const (
	placeholderServerURL     = "<watchtower-server-url>"
	placeholderServerToken   = "<watchtower-auth-token>"
	placeholderContainerName = "<gnoland-container-name>"
	placeholderConfigPath    = "<path-to-gnoland-config>"
	placeholderJournaldUnit  = "<gnoland-systemd-unit>"
)

// IsPlaceholder reports whether s is an unresolved placeholder value.
func IsPlaceholder(s string) bool {
	return len(s) > 2 && s[0] == '<' && s[len(s)-1] == '>'
}

type Config struct {
	Server    ServerConfig    `toml:"server" comment:"Connection to the watchtower server (or an intermediate beacon)"`
	Beacon    BeaconConfig    `toml:"beacon,omitempty" comment:"Noise keys, required when server.url uses the noise:// scheme"`
	RPC       RPCConfig       `toml:"rpc" comment:"RPC status collector"`
	Logs      LogsConfig      `toml:"logs" comment:"Log collector"`
	OTLP      OTLPConfig      `toml:"otlp" comment:"OpenTelemetry relay"`
	Resources ResourcesConfig `toml:"resources" comment:"System resource monitor"`
	Metadata  MetadataConfig  `toml:"metadata" comment:"Config metadata collector"`
	Self      SelfConfig      `toml:"self" comment:"Sentinel self-stats collector (pipeline health: bytes sent, drops, retries)"`
	Health    HealthConfig    `toml:"health" comment:"Sentinel health endpoint"`
}

// ServerConfig holds the upstream destination. The URL scheme selects
// transport:
//
//	https://...  — direct to watchtower, standard TLS
//	noise://...  — through a beacon on the sentry; requires [beacon] keys_dir
//
// The token travels in the Authorization header regardless of transport. When
// routed via a beacon, the beacon passes the header through unchanged — the
// watchtower is still the ultimate authenticator.
type ServerConfig struct {
	URL   string `toml:"url"`
	Token string `toml:"token"`
}

// BeaconConfig holds the Noise-specific parameters used when server.url has
// the noise:// scheme. See pkg/noise for the four auth modes selected by
// whether public_key and authorized_keys are set.
type BeaconConfig struct {
	// KeysDir holds <KeysDir>/privkey (0600) and <KeysDir>/pubkey (0644)
	// generated by `sentinel keygen`. Required when the URL is noise://.
	KeysDir string `toml:"keys_dir,omitempty"`
	// PublicKey, if non-empty, pins the beacon's expected static public key:
	// the sentinel refuses handshakes where the responder's key doesn't match.
	// 64 hex characters. When empty, sentinel accepts any beacon (the
	// handshake still provides confidentiality vs passive eavesdroppers).
	PublicKey string `toml:"public_key,omitempty"`
}

type RPCConfig struct {
	Enabled                    bool     `toml:"enabled"`
	PollInterval               Duration `toml:"poll_interval"`
	RPCURL                     string   `toml:"rpc_url"`
	DumpConsensusStateInterval Duration `toml:"dump_consensus_state_interval"`
	GenesisRefreshInterval     Duration `toml:"genesis_refresh_interval" comment:"re-fetch and re-emit /genesis at this interval (0 = 12h default)"`
}

// LogsConfig holds log collector settings.
type LogsConfig struct {
	Enabled        bool     `toml:"enabled"`
	Source         string   `toml:"source" comment:"docker or journald"`
	ContainerName  string   `toml:"container_name,omitempty" comment:"docker source only"`
	JournaldUnit   string   `toml:"journald_unit,omitempty" comment:"journald source only"`
	BatchSize      ByteSize `toml:"batch_size"`
	BatchTimeout   Duration `toml:"batch_timeout"`
	MinLevel       string   `toml:"min_level" comment:"debug, info, warn, or error"`
	ResumeLookback Duration `toml:"resume_lookback" comment:"on restart, re-read logs from this far back (docker only)"`
}

// OTLPConfig holds OTLP relay settings.
type OTLPConfig struct {
	Enabled    bool   `toml:"enabled"`
	ListenAddr string `toml:"listen_addr"`
}

// ResourcesConfig holds resource monitor settings.
type ResourcesConfig struct {
	Enabled       bool     `toml:"enabled"`
	PollInterval  Duration `toml:"poll_interval"`
	Source        string   `toml:"source" comment:"host, docker, or both"`
	ContainerName string   `toml:"container_name,omitempty"`
}

// MetadataConfig holds metadata collector settings.
// For config: set exactly one of config_path or config_get_cmd — setting both
// is an error. The binary version is obtained from /status.node_info.version
// (RPC pipeline), and genesis info from /genesis — neither needs to be
// collected out-of-band anymore.
type MetadataConfig struct {
	Enabled       bool     `toml:"enabled"`
	CheckInterval Duration `toml:"check_interval"`
	ForceInterval Duration `toml:"force_interval" comment:"re-emit config regardless of changes at this interval (0 = 12h default)"`

	ConfigPath   string `toml:"config_path,omitempty"`
	ConfigGetCmd string `toml:"config_get_cmd,omitempty" comment:"use %s as placeholder for the config key name"`
}

// SelfConfig holds the sentinel self-stats collector settings. The collector
// reports absolute counters (bytes sent, drops, retries) per data type so the
// watchtower can export them as Prometheus counters for pipeline dashboards.
type SelfConfig struct {
	Enabled        bool     `toml:"enabled"`
	ReportInterval Duration `toml:"report_interval"`
}

// HealthConfig holds the sentinel health endpoint settings.
type HealthConfig struct {
	Enabled    bool   `toml:"enabled"`
	ListenAddr string `toml:"listen_addr"`
}

func Load(path string) (*Config, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("load config %s: %w", path, err)
	}
	var cfg Config
	if err := toml.Unmarshal(data, &cfg); err != nil {
		return nil, fmt.Errorf("load config %s: %w", path, err)
	}
	if err := cfg.validate(); err != nil {
		return nil, fmt.Errorf("invalid config: %w", err)
	}
	return &cfg, nil
}

// DefaultConfig returns a Config with sensible defaults.
// Unknown values use angle-bracket placeholders.
func DefaultConfig() *Config {
	return &Config{
		Server: ServerConfig{
			URL:   placeholderServerURL,
			Token: placeholderServerToken,
		},
		RPC: RPCConfig{
			Enabled:                    true,
			PollInterval:               Duration{Duration: 3 * time.Second},
			RPCURL:                     "http://localhost:26657",
			DumpConsensusStateInterval: Duration{Duration: 30 * time.Second},
		},
		Logs: LogsConfig{
			Enabled:        true,
			Source:         LogSourceDocker,
			ContainerName:  placeholderContainerName,
			BatchSize:      ByteSize(mb),
			BatchTimeout:   Duration{Duration: 5 * time.Second},
			MinLevel:       "info",
			ResumeLookback: Duration{Duration: 60 * time.Second},
		},
		OTLP: OTLPConfig{
			Enabled:    true,
			ListenAddr: "localhost:4318",
		},
		Resources: ResourcesConfig{
			Enabled:       true,
			PollInterval:  Duration{Duration: 10 * time.Second},
			Source:        ResSourceHost,
			ContainerName: placeholderContainerName,
		},
		Metadata: MetadataConfig{
			Enabled:       true,
			CheckInterval: Duration{Duration: 10 * time.Minute},
			ConfigPath:    placeholderConfigPath,
		},
		Self: SelfConfig{
			Enabled:        true,
			ReportInterval: Duration{Duration: 30 * time.Second},
		},
		Health: HealthConfig{
			Enabled:    true,
			ListenAddr: "127.0.0.1:8081",
		},
	}
}

func (c *Config) anyCollectorEnabled() bool {
	return c.RPC.Enabled || c.Logs.Enabled || c.OTLP.Enabled || c.Resources.Enabled || c.Metadata.Enabled || c.Self.Enabled
}

// isNoiseScheme returns true when the server URL uses noise://, i.e. when
// traffic is routed through a beacon instead of directly to the watchtower.
func (c *Config) isNoiseScheme() bool {
	return strings.HasPrefix(c.Server.URL, "noise://")
}

// validateBeacon enforces the coupling between server.url scheme and
// [beacon]: noise:// requires keys_dir; public_key requires noise://.
func (c *Config) validateBeacon() error {
	noise := c.isNoiseScheme()
	if noise && c.Beacon.KeysDir == "" {
		return fmt.Errorf("beacon.keys_dir is required when server.url uses noise://")
	}
	if !noise && c.Beacon.KeysDir != "" {
		return fmt.Errorf("beacon.keys_dir is only meaningful when server.url uses noise://")
	}
	if !noise && c.Beacon.PublicKey != "" {
		return fmt.Errorf("beacon.public_key is only meaningful when server.url uses noise://")
	}
	return nil
}

// NoiseConfig builds a pkg/noise.Config from the beacon section, loading the
// static keypair from disk. Returns nil when the URL scheme isn't noise://
// (callers pass the nil through to sender.New, which falls back to HTTPS).
func (c *Config) NoiseConfig() (*noisepkg.Config, error) {
	if !c.isNoiseScheme() {
		return nil, nil
	}
	kp, err := noisepkg.LoadKeypair(c.Beacon.KeysDir)
	if err != nil {
		return nil, fmt.Errorf("load beacon keypair: %w", err)
	}
	cfg := &noisepkg.Config{Static: kp}
	if c.Beacon.PublicKey != "" {
		pub, err := noisepkg.DecodePublicKey(c.Beacon.PublicKey)
		if err != nil {
			return nil, fmt.Errorf("beacon.public_key: %w", err)
		}
		cfg.AuthorizedKeys = [][]byte{pub}
	}
	return cfg, nil
}

func (c *Config) validate() error {
	if c.anyCollectorEnabled() {
		if c.Server.URL == "" {
			return fmt.Errorf("server.url is required when a collector is enabled")
		}
		if c.Server.Token == "" {
			return fmt.Errorf("server.token is required when a collector is enabled")
		}
	}
	if err := c.validateBeacon(); err != nil {
		return err
	}
	if c.Health.Enabled && c.Health.ListenAddr == "" {
		return fmt.Errorf("health.listen_addr is required when health is enabled")
	}
	if c.Metadata.Enabled && c.Metadata.ConfigPath != "" && c.Metadata.ConfigGetCmd != "" {
		return fmt.Errorf("metadata: set exactly one of config_path or config_get_cmd, not both")
	}
	if c.Logs.Enabled {
		validLogSources := []string{LogSourceDocker, LogSourceJournald}
		if !slices.Contains(validLogSources, c.Logs.Source) {
			return fmt.Errorf("logs.source %q: must be one of %v", c.Logs.Source, validLogSources)
		}
		if !slices.Contains(validLogLevels, c.Logs.MinLevel) {
			return fmt.Errorf("logs.min_level %q: must be one of %v", c.Logs.MinLevel, validLogLevels)
		}
	}
	if c.Resources.Enabled {
		validResSources := []string{ResSourceHost, ResSourceDocker, ResSourceBoth}
		if !slices.Contains(validResSources, c.Resources.Source) {
			return fmt.Errorf("resources.source %q: must be one of %v", c.Resources.Source, validResSources)
		}
	}
	return nil
}
