// Package config defines the beacon's TOML configuration schema + loader.
package config

import (
	"fmt"
	"os"
	"strings"
	"time"

	toml "github.com/pelletier/go-toml/v2"

	noisepkg "github.com/aeddi/gno-watchtower/pkg/noise"
	"github.com/aeddi/gno-watchtower/pkg/tomlutil"
)

// Duration wraps time.Duration for TOML string values like "3s", "30s".
type Duration = tomlutil.Duration

// Placeholder values used in generated configs.
const (
	placeholderUpstream   = "<watchtower-url>"
	placeholderKeysDir    = "<path-to-beacon-keys-dir>"
	placeholderConfigPath = "<path-to-gnoland-config>"
	placeholderRPCURL     = "http://localhost:26657"
)

// Config is the root beacon configuration.
type Config struct {
	Server   ServerConfig   `toml:"server" comment:"Upstream watchtower destination (HTTPS) and bearer-token passthrough behaviour"`
	Beacon   BeaconConfig   `toml:"beacon" comment:"Noise listener: keys, listen address, optional sentinel allowlist"`
	RPC      RPCConfig      `toml:"rpc" comment:"Sentry's gnoland RPC endpoint — fetched per /rpc forward to augment the payload"`
	Metadata MetadataConfig `toml:"metadata,omitempty" comment:"Sentry's gnoland config access — set exactly one of config_path or config_get_cmd (matches sentinel's [metadata] shape)"`
}

// ServerConfig holds the upstream watchtower endpoint. The beacon forwards
// the sentinel's bearer token unchanged, so it must trust this URL to be the
// real watchtower.
type ServerConfig struct {
	URL string `toml:"url"`
}

// BeaconConfig configures the Noise listener.
type BeaconConfig struct {
	ListenAddr string `toml:"listen_addr"`

	// KeysDir holds <KeysDir>/privkey (0600) and <KeysDir>/pubkey (0644)
	// generated by `beacon keygen`.
	KeysDir string `toml:"keys_dir"`

	// AuthorizedKeys is the optional allowlist of sentinel public keys this
	// beacon accepts; when empty, any sentinel may connect (the handshake
	// still provides confidentiality and session-key forward secrecy, but not
	// authentication of the sentinel's identity). 64-hex-character strings.
	AuthorizedKeys []string `toml:"authorized_keys,omitempty"`

	// HandshakeTimeout bounds the Noise handshake phase; keeps slow-loris
	// attackers from tying up file descriptors. 5s default.
	HandshakeTimeout Duration `toml:"handshake_timeout"`
}

// RPCConfig holds the sentry's gnoland RPC endpoint used for augmenting
// /rpc forwards.
type RPCConfig struct {
	RPCURL string `toml:"rpc_url"`
}

// MetadataConfig mirrors sentinel's [metadata] — exactly one of ConfigPath or
// ConfigGetCmd must be set when augmentation of config keys is wanted.
// Leaving both empty disables config augmentation (peers + info still work).
type MetadataConfig struct {
	ConfigPath    string   `toml:"config_path,omitempty"`
	ConfigGetCmd  string   `toml:"config_get_cmd,omitempty" comment:"use %s as placeholder for the config key name"`
	ForceInterval Duration `toml:"force_interval,omitempty" comment:"augment sentry_* keys at least this often even when net_info is absent (0 = 12h default)"`
}

// DefaultConfig returns a Config with sensible defaults and placeholders.
func DefaultConfig() *Config {
	return &Config{
		Server: ServerConfig{
			URL: placeholderUpstream,
		},
		Beacon: BeaconConfig{
			ListenAddr:       "0.0.0.0:8080",
			KeysDir:          placeholderKeysDir,
			HandshakeTimeout: Duration{Duration: 5 * time.Second},
		},
		RPC: RPCConfig{
			RPCURL: placeholderRPCURL,
		},
		Metadata: MetadataConfig{
			ConfigPath: placeholderConfigPath,
		},
	}
}

// Load parses the TOML config file at path.
func Load(path string) (*Config, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("load config %s: %w", path, err)
	}
	var cfg Config
	if err := toml.Unmarshal(data, &cfg); err != nil {
		return nil, fmt.Errorf("load config %s: %w", path, err)
	}
	if err := cfg.validate(); err != nil {
		return nil, fmt.Errorf("invalid config: %w", err)
	}
	return &cfg, nil
}

// Generate writes an annotated example TOML config to path. Same shape as
// sentinel and watchtower's generate-config output: placeholders use
// angle-bracket syntax that IsPlaceholder detects.
func Generate(path string) error {
	cfg := DefaultConfig()
	data, err := toml.Marshal(cfg)
	if err != nil {
		return fmt.Errorf("marshal config: %w", err)
	}
	return os.WriteFile(path, data, 0o644)
}

// IsPlaceholder reports whether s is an unresolved angle-bracket placeholder.
func IsPlaceholder(s string) bool {
	return len(s) > 2 && s[0] == '<' && s[len(s)-1] == '>'
}

func (c *Config) validate() error {
	if c.Server.URL == "" {
		return fmt.Errorf("server.url is required")
	}
	if !IsPlaceholder(c.Server.URL) &&
		!strings.HasPrefix(c.Server.URL, "http://") && !strings.HasPrefix(c.Server.URL, "https://") {
		return fmt.Errorf("server.url must be http:// or https://, got %q", c.Server.URL)
	}
	if c.Beacon.ListenAddr == "" {
		return fmt.Errorf("beacon.listen_addr is required")
	}
	if c.Beacon.KeysDir == "" {
		return fmt.Errorf("beacon.keys_dir is required")
	}
	if c.RPC.RPCURL == "" {
		return fmt.Errorf("rpc.rpc_url is required")
	}
	if c.Metadata.ConfigPath != "" && c.Metadata.ConfigGetCmd != "" {
		return fmt.Errorf("metadata: set exactly one of config_path or config_get_cmd, not both")
	}
	for i, k := range c.Beacon.AuthorizedKeys {
		if _, err := noisepkg.DecodePublicKey(k); err != nil {
			return fmt.Errorf("beacon.authorized_keys[%d]: %w", i, err)
		}
	}
	return nil
}

// NoiseConfig builds the pkg/noise.Config from the loaded TOML.
func (c *Config) NoiseConfig() (*noisepkg.Config, error) {
	kp, err := noisepkg.LoadKeypair(c.Beacon.KeysDir)
	if err != nil {
		return nil, fmt.Errorf("load keypair: %w", err)
	}
	cfg := &noisepkg.Config{Static: kp}
	if len(c.Beacon.AuthorizedKeys) > 0 {
		cfg.AuthorizedKeys = make([][]byte, 0, len(c.Beacon.AuthorizedKeys))
		for _, k := range c.Beacon.AuthorizedKeys {
			pub, err := noisepkg.DecodePublicKey(k)
			if err != nil {
				return nil, fmt.Errorf("authorized_keys: %w", err)
			}
			cfg.AuthorizedKeys = append(cfg.AuthorizedKeys, pub)
		}
	}
	return cfg, nil
}
